### ISSUE TITLE
ceph-rook - [feature] rgw Keystone and Swift integration

### ISSUE THREAD

**Issue by yeoldegrove** [osism/issues#1027]
Rook currently does not support configuration of rgw for Keystone and Swift integration out of the box.
See current efforts to change this:
- https://github.com/rook/rook/issues/9088
- https://github.com/rook/rook/pull/9444
- https://github.com/rook/rook/pull/13807
- https://github.com/rook/rook/pull/13808

**Comment by b1-lender** [comment]
The `testbed` environment was a bit unstable which caused delay on getting initial tests running. Later on I had to restart the kubernetes cluster often to continue testing. Further delay was caused by the change https://github.com/osism/testbed/commit/2a6558f0338712c723dfb921029b7d97a0587520 that I was unaware of. Recently I was able to get a connection but testing the access was unsuccessful with the message `Unauthorized (HTTP 401)`.
