### ISSUE TITLE
no vault pass prompt when using python-osism

### ISSUE THREAD

**Issue by linwalth** [osism/issues#152]
When I use OSISM with osismclient (à la osism apply configuration) I am not prompted for a password and I cannot set the --ask-vault-pass parameter since the command already implies --vault-pass-file.

**Comment by berendt** [comment]
Vault Integration will be implemented there in this (4.0.0) cycle. Until then, you still have to use the old ``osism-*`` commands for Vault.

**Comment by linwalth** [comment]
thank you for the quick answer!

**Comment by berendt** [comment]
Also it is not yet possible to set the Ansible vault password via the python-osism CLI.

For the moment you can set the used password in the password file in the configuration repository (instead of the script). Please be aware that this could be a security risk. You could minimise the security risk a little bit by using encrypted file systems.

**Comment by berendt** [comment]
Duplicate of https://github.com/osism/python-osism/issues/83. Let's track this in python-osism.
