### ISSUE TITLE
manager: document "osism.manager.keypair could not be found"

### ISSUE THREAD

**Issue by berendt** [osism/issues#192]
```
ERROR! the playbook: osism.manager.keypair could not be found
ERROR! the playbook: osism.manager.manager could not be found
```

Occurs when using osism-update-manager or ./run.sh in the manager environment if the Ansible version used is too old.

.venv directory in the manager environment must be deleted. Afterwards it works again.

**Comment by Nils98Ar** [comment]
@berendt Could we always use a separate (supported) version of ansible in the osism-update-manager script instead of checking if there is already an installed version available?

Or add least add a pre-check if the installed version is compatible?

In the last two upgrade we had issues with the osism-update-manager script that where caused by a wrong version of ansible on the system.

**Comment by Nils98Ar** [comment]
Maybe always ansible in a container would be an option?
