### ISSUE TITLE
Automatic renewal of (letsencrypt) certificates

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#215]
Hi,

I want to renew our Openstack-api letsencrypt certificates in an automated fashion. This involves two steps:
* running certbot to fetch new certificates
* Running "osism-kolla reconfigure loadbalancer" to apply those

As for the latter it is currently a manual process as I need a password to unlock Ansible's vault. However, I want this to run as a cron job. How can I achieve this?

As for osism cli there is a special command osism-run-without-secrets.sh: https://github.com/osism/container-image-osism-ansible/blob/5e9fece44c4996814d80b33021d39b15c09aa625/files/scripts/run-without-secrets.sh

Any chance to get this also for https://github.com/osism/container-image-kolla-ansible ?
Or is there another alternative?

Kind regards,
André.

**Comment by berendt** [comment]
I mean certbot would be already present in Kolla.

We had never adapted this on our site, as we had previously focused on on-premise clouds where some internal CA was always used.

Letsencrypt was never usable because there was never any external connectivity or an other proxy in front of the Haproxy proxy provided by Kolla that took care of it.

I would suggest that we should discuss and record the requirements for the certificates in general and then identify how it is currently implemented and how it should be implemented in the future.

Does that make sense to you? Then I would take it to Team 1 next Wednesday and have Felix schedule it there.

**Comment by nerdicbynature** [comment]
Yes, that's fine for me. Markus is probably also present at the meeting so he might share more details on this. 

I just wanted to drop a note here and re-check whether there already is a mechanism that I haven't noticed already.

**Comment by berendt** [comment]
In Kolla, only the pass-through of http-01 is currently implemented in Horizon. You have to take care of certbot service yourself. You just set where requests for the http-01 well-known URL should be redirected to.

The same applies to getting the certificates generated by certbot into the appropriate place in the configuration repository.

When initializing a new environment, you must first use the certbot without Horizon (but with Keepalived/Haproxy) because Horizon is not yet usable at this point.

I currently tend to only document how to generate a new certificate via certbot (installed via package) and http-01. The rest can be added manually depending on the environment.

**Comment by nerdicbynature** [comment]
Well.. I think the discussion went a little bit into the wrong direction

Enabling certbot was not my focus.

My original intention was to let "osism-kolla reconfigure loadbalancer" run via cron without password. This would enable us to renew certs automatically. As Letsencrypt certs are only valid for three months it's quite a burden to renew them all manually.

**Comment by berendt** [comment]
Is that still necessary? If yes, please re-open it.

Run of plays without vault is already possible via ``osism-run-without-secrets``. But I think it's not a good idea to not encrypt the SSL private keys.
