### ISSUE TITLE
Ansible lint: Discussion default rules

### ISSUE THREAD

**Issue by ra-rau** [osism/issues#237]
Here is a full list which rules we can enable and disable by default:
https://ansible-lint.readthedocs.io/en/latest/default_rules/

I choose some of them for enabling and some for disabling. Here my choices:

Linting yes:
command-instead-of-module
command-instead-of-shell
deprecated-bare-vars
deprecated-command-syntax
deprecated-local-action
deprecated-module
fqcn-builtins
key-order
load-failure
no-changed-when
no-jinja-nesting
no-jinja-when
no-loop-var-prefix
no-relative-paths
package-latest
parser-error
partial-become
playbook-extension
risky-file-permissions
risky-octal
risky-shell-pipe
role-name
schema
syntax-check
unnamed-task
var-naming
var-spacing
yaml

Linting no:
git-latest
hg-latest
ignore-errors
inline-env-var
meta-no-info
meta-incorrect
meta-no-tags
meta-video-links
no-handler

Don´t know: 
internal-error
literal-compare
no-tabs

I think we have to discuss it in the team, which rules we want to enable and which not. Some are required and can not be disabled.

**Comment by osfrickler** [comment]
inline-env-var seems reasonable to me, why would you not want it?

I definitively would add no-tabs and likely literal-compare. internal-error shouldn't matter until we actually trigger one.

I don't agree with package-latest, version handling should be done in the local repo mirror IMO.

Unsure about yaml, in some repos at least we do a dedicated yamllint run, so that would be redundant. Not sure whether we can find a common ground for that or whether it will be repo-specific.

**Comment by ra-rau** [comment]
Package latest is not for installing the latest version. Package latest will check that the latest tag is NOT used. If you add this tag, you dont be able to use latest you have to choose a version number or no version.

Here the phrase from the documentation:
"package-latest
Package installs should not use latest.

Package installs should use state=present with or without a version"

**Comment by tibeer** [comment]
no-tabs is problematic. if you have j2 templates which require tabs this get's triggered, too (at least it was like this some time ago). inline-env-var had a reason, but i cannot remember the cause. I think this was because of subshells not receiving the environment variables if presented via "environment:".

**Comment by osfrickler** [comment]
> Package latest is not for installing the latest version. Package latest will check that the latest tag is NOT used. If you add this tag, you dont be able to use latest you have to choose a version number or no version.
> 
> Here the phrase from the documentation: "package-latest Package installs should not use latest.
> 
> Package installs should use state=present with or without a version"

Yes, exactly. I claim package installs with state=latest are a good thing.

**Comment by ra-rau** [comment]
But didn´t we have many issues in the past where latest was the reason? I think latest, should be a good thing, but does not work fine at the moment for us.

**Comment by ra-rau** [comment]
I am closing this issue since the checks are now integrated.
