### ISSUE TITLE
Discuss if the elasticsearch-curator service should be enabled by default

### ISSUE THREAD

**Issue by berendt** [osism/issues#272]
Related to https://github.com/osism/testbed/issues/1260

**Comment by berendt** [comment]
If yes: what should be used as default retention time?

**Comment by linwalth** [comment]
Regarding the premise of the issue: Yes, absolutely, because at some point someone will run into storage problems with it, having rolled it with default vars.

Regarding the time, IMHOO (in my humble opinionated opinion):

5d soft-delete / 7d hard-delete seems fine enough regarding storage capacity. Potentially 10d/14d soft/hard-delete. Anyone else invested in a longer retention time will most likely look into the limits themselves and configure them according to their specs.

**Comment by fkr** [comment]
imho @linwalth's proposition sounds good.

**Comment by berendt** [comment]
Would prefer the 10/14 days thing. This way we have a weekend or longer public holiday phase covered in any case.

**Comment by tibeer** [comment]
You definitely want to enable it by default. Normally the term used by elasticsearch for index rotation is "phase".
https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-index-lifecycle.html
Of course there is no typical setup, but from what I've heard is that almost all logs are rotated after 14 days, no matter how big the company was. Audit data is different though. These may be kept for as long as 2 years.

**Comment by frosty-geek** [comment]
I think 5/7 is a good default depending on your situation. 

I would assume that logfile will be forwarded to an "off-site"/central logfile dump if you have more specific needs for longer retention/special use-cases (collect several sites into one)/audit logs.

**Comment by berendt** [comment]
5/7 as default is also fine for me.
