### ISSUE TITLE
E:Could not open lock file /var/lib/apt/lists/lock - open (2: No such file or directory)"

### ISSUE THREAD

**Issue by berendt** [osism/issues#274]
Fresh system. Called via ``./run.sh network``.

```
TASK [osism.commons.network : Install required packages] ************************************************************************************
fatal: [20-02]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (2: No such file or directory)"}
```

Works after a manual ``sudo apt-get update`` on the system.

**Comment by osfrickler** [comment]
This looks like an additional (new?) path that would be needed to our lock waiter in front of every ansible task. But maybe this is no longer necessary once we can rely on ansible 2.12, since it has added a lock wait mechanism, possibly we'd just want to increase the timeout (default is 60s): https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-lock_timeout

**Comment by berendt** [comment]
Would prefer to use the lock timeout in the apt task and to remove the lock mechanism. I think we can do this after the next release.
