### ISSUE TITLE
Improve operator role

### ISSUE THREAD

**Issue by berendt** [osism/issues#280]
The operator role is used to provide the account used as deployment user. This should be improved.

* The rights of the deployment user should be restricted. Only what is needed should be enabled via sudoers.
* Besides the deployment user there should be a real operator user
  * dragon -> deployment user
  * some cool name -> operator user

**Comment by frosty-geek** [comment]
FYI

We've steered away from the concept of a generic operator user in favor of multiple named operator users. Main reason behind this is certification audits and it's easier to just answer "yes" instead of giving a reasoning why generic accounts are used (which I believe is still valid).

The dragon user still exists as discussed above.

Ralf

**Comment by berendt** [comment]
The operator user concept itself needs to be discussed. I will take this to one of the next SCS meetings. Detailed issues may then follow. This can be closed for now.
