### ISSUE TITLE
ceph upgrade fails because of ansible version

### ISSUE THREAD

**Issue by maliblatt** [osism/issues#293]
In a fresh upgraded manager the ceph upgrade fails because of a wrong ansible version:
`TASK [ceph-validate : fail on unsupported ansible version] 

fatal: [control01]: FAILED! => {"changed": false, "msg": "Ansible version must be 2.10!"}
`
ceph-ansible container Version shows up as:
Ansible version: 2.9.27
Container version: 3.2.0

seems that ansible should be upgraded ?!

**Comment by berendt** [comment]
We currently use Ansible 2.9 in the container instead of Ansible 2.10. I will adapt this with the next release. Regardless of this, everything works. Only ceph-validate fails at the moment.

But so far we have not included ceph-validate anywhere either. In any case, this would be a good addition to do by default.
