### ISSUE TITLE
OSISM should automatically generate SSH key for Neutron amongst others

### ISSUE THREAD

**Issue by linwalth** [osism/issues#305]
Updating an existing OpenStack installation to a Kolla Version >= Yoga generates an issue with the neutron upgrade because neutron, per default, expects an ssh key for ansible management of switches and routers.

https://github.com/openstack/kolla-ansible/blob/087d0e1d60d867ba12f010e77fe92c73960f2df7/doc/source/reference/networking/neutron.rst#ssh-authentication-in-external-systems-switches

Kolla has a built-in mechanism for creation of said key. **OSISM should leverage this functionality.**
https://github.com/openstack/kolla-ansible/blob/9549e8ccfe5d7a047b0a1a4754d06cd4b0cfde9e/kolla_ansible/cmd/genpwd.py#L124

Suggested to me by https://github.com/DeadRabb1t - please keep him in the loop too.

**Comment by berendt** [comment]
It is noted in the release notes that this parameter must be added.

Since the secrets.yml file is in the configuration repository, there is no way for OSISM to add anything to it since it is assumed that the configuration repository on the manager is read only.

The genpwd.py script is already used in Cookiecutter to generate Kolla's secrets.yml file when a new repository is created.

**Comment by berendt** [comment]
The only thing I can think of is to write a script that takes the current secrets.yml (Yoga) and compares it with a secrets.yml in the config repo (before Yoga) and lists non-existent secrets and generates content for them. Then you can insert that.

Then you wouldn't have to think about it and generate anything by hand.

**Comment by berendt** [comment]
The comparison of the secrets will be included in a validate command. The rest is done. I'm closing this.
