### ISSUE TITLE
ansible-lint: Jinja templates should only be at the end of 'name' (name[template])

### ISSUE THREAD

**Issue by berendt** [osism/issues#323]
New ansible-lint version, new fun. Please check all repositories for ```Jinja templates should only be at the end of 'name' (name[template])```.

This is an example from the ```osism/testbed``` repository.

```
name: Jinja templates should only be at the end of 'name' (name[template])
environments/custom/playbook-keycloak-oidc-client-config.yml:82 Task/Handler: Get internal ID for {{ keystone_client_id }} client

name: Jinja templates should only be at the end of 'name' (name[template])
environments/custom/playbook-keycloak-oidc-client-config.yml:94 Task/Handler: Filter internal ID for {{ keystone_client_id }} client
```

Should be something like ```Filter internal ID for the client {{ keystone_client_id }}``` and ```Get internal ID for the client {{ keystone_client_id }}```.

**Comment by berendt** [comment]
Kolla decided to exclude this rule: https://review.opendev.org/c/openstack/kolla-ansible/+/859220. We will do the same.

**Comment by ra-beer** [comment]
I updated the Ansible-Lint-Rules as them have changed a lot of things in the last update. In a follow up Issue (https://github.com/osism/issues/issues/326) i will fix the upcoming warnings. For the Issues described above: I added the name[template] to the skip_list where it was necessary.
So this issue is done and can be closed.

**Comment by berendt** [comment]
Looks like this is done.
