### ISSUE TITLE
How to best run OpenStack trademark tests

### ISSUE THREAD

**Issue by garloff** [osism/issues#425]
As certification tester, I want to have a simple way to test an OpenStack cloud for OpenStack Powered Compute 20xx.yy compliance.

## Background:
We have the scs-compliance-check.py[https://github.com/SovereignCloudStack/standards/blob/main/Design-Docs/tools/scs-compliance-check.py] tool which processes the scs-compliant.yaml[https://github.com/SovereignCloudStack/standards/blob/main/Design-Docs/tools/scs-compatible.yaml] spec to read the list of standards that need to be complied to along with a list of tests that is associated with each standards. Each test tool at the IaaS layer can assume to have OS_CLOUD set to a cloud with normal tenant user access and a working openstacksdk installed.

Note: Running tests without special privileges is a design decision: Test should not normally require any admin level power, as this would prevent normal customers from using a validation tool and would also bring various security concerns.

Currently, we (as per our documentation) require OpenStack powered Compute 2020.11 compliance, yet we don't have a test tool that goes out and checks. What we need is an executable that can be called and returns an error code (and optionally produces a yaml report.)

## Options how to implement this:
- Enhance required environment by a few more packages (available on popular Linux distros)
- Set up a venv in which the tempest and refstack tools get deployed and run the tests
- Download a docker container in which to run all these tests for us (maybe OSISM has one that can be reused?)
- Query a refstack server that we can trust (OIF, ...) for current results

Probably there are more options.

Please discuss and provide advice how to best move forward.

**Comment by berendt** [comment]
At the moment we have https://github.com/osism/testbed/tree/main/contrib/refstack for this.

Not sure what to do here now? Should this be provided in a separate repository?

**Comment by garloff** [comment]
I am on a Linux machine, have the openstacksdk installed and tenant user access to the cloud that I want to test.
Under these conditions, I can run the included tests to check compliance with e.g. the flavor-naming and image-metadata specs. (I could as well run the openstack-health-monitor which has the same modest requirements.)

Likewise, I would like to run an executable that does run all the tempest tests required for the OpenStack Powered Compute Guidelines and collects the results.

This may require us to ensure additional software is installed (be it standard Linux packages or python-venv or pip installed packages) or it may require to build a docker container to have a well-enough defined environment.
The referenced refstack repo may have most of what's needed, I can't judge this without having a README.md ...
In the end, I want to call an executable and get a yaml report and an exit code back.

**Comment by berendt** [comment]
The documentation for contrib/refstack is in the testbed documentation, not in a separate README.md.

There are 2 things to do:

1. Move contrib/refstack to a role so that it is not only usable in the testbed + add documentation in osism/documentation on how to use the new role
2. Add a role to perform additional validations (images, flavors, ...)

**Comment by berendt** [comment]
There is a new command osism validate refstack. This command will install refstack + all requirements on a defined manager node. It will also prepare all required configuration files + test project, flavor, network...

At the moment, all you have to do is to prepare a clouds.yaml in /opt/configuration/environments/openstack/.

Since the new command is based on a role imported from contrib/refstack of the testbed, it currently only works on the testbed itself.

This can then be expanded so that it also works independently and existing SCS flavours and images can be used.
