### ISSUE TITLE
Test if we can upgrade to openstacksdk to v1

### ISSUE THREAD

**Issue by berendt** [osism/issues#447]
openstacksdk v1 should be used in all Ansible (with ansible-core 2.14.x) and manager images if possible.

**Comment by osfrickler** [comment]
Updating to sdk 1.0.1 needs to be combined with updating to ansible-collections-openstack v2.0, cf. https://review.opendev.org/c/openstack/kolla/+/874725, we'll have to check where the latter is being used. Since Kolla is making the switch only for the 2023.1 cycle now, maybe we should also prefer to work on this for the next release, not the current one.

**Comment by berendt** [comment]
Let's wait for Kolla 2023.1 cycle.
