### ISSUE TITLE
Add more zuul nodes

### ISSUE THREAD

**Issue by berendt** [osism/issues#452]
With the switch from Github Actions to Zuul, we now have many more jobs running on Zuul. At the moment, it takes quite a long time for individual jobs to be executed because there are too few prepared nodes. The number of prepared nodes should be increased significantly to reduce the waiting time for PRs.

**Comment by osfrickler** [comment]
There are several aspects to this:

a) We currently have a min-ready of 2 ubuntu-jammy nodes, but I don't think that this is a big issue, since booting and setting up a new test node doesn't take longer than a minute, so shouldn't matter too much except for very short jobs.

b) We currently have a quota of 4 total nodes, this is mainly due to lack of enough addresses in the floating IP pool, which is shared with addresses for the testbed CI nodes and only comprises a /28 in total. So in particular the is not much room for increasing the min-ready nodes, since if we would have always 4 jammy nodes running, there would be no quota left when a job requires a different node.

c) We could look into either increasing the FIP pool, using IPv6 space or using only local addresses (since the zuul setup is co-hosted with the test nodes), but maybe adding in resources from a different cloud would be better, also increasing resilience?

d) I noticed that the real issue with slow check results seems to be that deleting used nodes seems to take a long time, like

```
harbott@zuul01-nbg1:~$ sudo docker exec -it zuul_nodepool_launcher nodepool list
+------------+----------------+------------------------------+--------------------------------------+---------------+------+----------+-------------+----------+
| ID         | Provider       | Label                        | Server ID                            | Public IPv4   | IPv6 | State    | Age         | Locked   |
+------------+----------------+------------------------------+--------------------------------------+---------------+------+----------+-------------+----------+
...
| 0000000514 | betacloud      | ubuntu-jammy                 | b9ec7eed-544f-4205-b4ca-315db4cd21e2 | 78.47.116.231 |      | deleting | 00:00:06:50 | locked   |
| 0000000517 | betacloud      | ubuntu-jammy                 | 600afbed-cb4e-4222-8e54-41f104befd0e | 78.47.116.231 |      | deleting | 00:00:03:49 | locked   |
| 0000000516 | betacloud      | ubuntu-jammy                 | 500ad4ab-0b5e-40ac-9c92-66de517bb649 | 78.47.116.238 |      | deleting | 00:00:04:40 | locked   |
| 0000000518 | betacloud      | ubuntu-jammy                 | 62cffc60-7614-4431-b3ae-e16d11f68f50 | 78.47.116.236 |      | deleting | 00:00:01:40 | locked   |
...
+------------+----------------+------------------------------+--------------------------------------+---------------+------+----------+-------------+----------+
```

I will try to investigate this on the cloud side, resolving this should likely help a lot with your issue.

**Comment by berendt** [comment]
Increase of min-ready from 2 to 4 and fix of deletion first.

Limit of 4 later.

**Comment by osfrickler** [comment]
Long deletion times seem to be an issue in latest nodepool code, see https://review.opendev.org/c/zuul/nodepool/+/862522/comments/df87471b_97009900

**Comment by osfrickler** [comment]
With the proposed fix applied locally, I no longer see long deletion times. Please reopen if you still see issues going forward.
