### ISSUE TITLE
Check if a specific Neutron/Octavia patch is part of our images

### ISSUE THREAD

**Issue by berendt** [osism/issues#499]

**Comment by garloff** [comment]
So, we need the Fix for floating IPs being ignored in the OVN loadbalancer health monitor.
Bug references:
https://bugs.launchpad.net/neutron/+bug/1956035
https://bugs.launchpad.net/neutron/+bug/1997418
Fix:
https://review.opendev.org/c/openstack/ovn-octavia-provider/+/873860
Cherry-pick for Zed:
https://review.opendev.org/c/openstack/ovn-octavia-provider/+/875595

**Comment by berendt** [comment]
As of https://github.com/SovereignCloudStack/issues/issues/268 the required patch is included.
