### ISSUE TITLE
openstack ironic images for ubuntu 22.04

### ISSUE THREAD

**Issue by schulze-b1** [osism/issues#527]
in the repo https://github.com/osism/openstack-ironic-images there is only the image for ubuntu 20.04. when can we expect an image (built recipe or prebuilt) for ubuntu 22.04?

**Comment by berendt** [comment]
The repository is intended more as an example of how to build for Ironic images. If you need images for Ubuntu 22.04 at short notice please open a PR. Otherwise, we are planning it, but it will take some time.

We currently tend to use https://github.com/osism/node-image with Virtual ISO per Ironic for deploying the Data Plane.

**Comment by berendt** [comment]
The repository has been archived. Ubuntu 22.04 images can be found here: https://github.com/b1-systems/openstack-ironic-images.
