### ISSUE TITLE
KVM Guest pauses/hold after Livemigration to Broadwell CPU's

### ISSUE THREAD

**Issue by zach-b1** [osism/issues#568]
After upgrade to Ubuntu 22 TLS, live migration from Server with CPU (Skylake, Cascadelake) to Server with Broadwell CPU don't work, only "openstack server reboot --hard" worked. 

CPU-Modell is "Broadwell" on all nodes.

[libvirt]
cpu_mode = custom
cpu_model = Broadwell-noTSX-IBRS
cpu_model_extra_flags = vmx

We tested this on openstack wallaby and zed (release 5.2)

**Comment by berendt** [comment]
Please check if you hit https://github.com/osism/issues/issues/521.

I think it is also a bad idea to live migrate things between different CPU types.

**Comment by svogt** [comment]
I've set the mentioned flag - yet still we got a a kernel panic. 

> I think it is also a bad idea to live migrate things between different CPU types.

In general I agree but we only have a handful of nodes per exact same CPU model and we do not really need the latest and greatest flags anyway, so we set all nodes in KVM/Qemu to use Broadwell as their arch. Worked well in the past.

**Comment by svogt** [comment]
Ok, also verified with latest HWE kernel (5.19) and after reboots, attached find the panic of the VM
[panic.txt](https://github.com/osism/issues/files/11915343/panic.txt)

**Comment by artificial-intelligence** [comment]
did you verify that the actual hardware cpu flags are exactly the same?

a kernel panic inside the guest vm indicates, that some operation could not be completed, most likely due to an instruction call not being present.

it's dangerous to specify your own custom cpu model if you haven't validated your complete hardware that it adheres to said spec.

also the topic says "kvm guest pauses/hold after Livemigration" but you write that the kernel panics, which is something different. are these two different bugs, or is it just a kernel panic? or does it panic after a reboot? that's not entirely clear.

**Comment by svogt** [comment]
we're not using our own, we use the kvm/qemu provided ones - regarding the issue name - initially we didn't see anything so it looked like it was paused, today i noticed one the  vm.unprivileged_userfaultfd=1 was set and i waited long enough, the kernel panic was visible in Openstacks console log

After (hard) reboot of the VM everthing works normal

**Comment by zach-b1** [comment]
Hi 

I think this is following bug:
https://bugs.launchpad.net/nova/+bug/1999814
https://review.opendev.org/q/I8ef9db851b37c5249d2efbe09a15a1ddbae8205d

**Comment by artificial-intelligence** [comment]
yes, I'm aware of such bugs, as you cited. That's why I advise to really double check if all deployed CPUs have all the same cpu flags available, because, especially with Intel, sadly you can't just assume that a newer model is a strict superset of an older model.

also, as can be seen in the mentioned openstack patch, openstack does it's own layering of checks on top of basic libvirt checks, which has led to inconsistencies in the past.

so my advice would be to evaluate your deployed CPUs and find a subset of flags which is supported by every CPU you have.

For running VMs that sadly means to reboot them, before you can migrate them, or cold migrate them, which is basically the same.

Do you need further assistance with this?

You can reach me also via the e-mail in my profile.

HTH

Sven

**Comment by svogt** [comment]
You're right, after checking the ACTUAL flags (not only what cpu models were reported) we saw a huge difference in flags, so the kernel panic is explainable. It looks like we're hit by serveral other bugs.
I can create a list of "valid" flags, question is how we can make a cpu map which we can then deploy on all instances. 

I think we can close this issue here for now, we can reopen or create a new one, once we've got Nova to use the same flags accross all instances...
