### ISSUE TITLE
Cephadm plans?

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#684]
Hi, do you have plans regarding `cephadm` [which seems to be the recommended way now](https://github.com/ceph/ceph-ansible#ceph-ansible)?

I came across this because of a [video from this year's OpenInfra Summit](https://www.youtube.com/watch?v=gjAI7lE9_zo) about deploying an active-active manila/cephfs/nfs-ganesha setup with cephadm.

**Comment by Nils98Ar** [comment]
I could only find issues/discussions from 2022 about this.

**Comment by berendt** [comment]
Please have a look at https://docs.ceph.com/en/latest/install for all available installers.

We currently do not plan to switch because ceph-ansible just works. It has been in productive use on many systems for years and it fully covers the user stories we currently need.

There will be an evaluation in SCS VP03 whether cephadm or rook will be supported in the future. Also whether or not features like CephFS or NFS should be supported in the future.

However, you can deploy and integrate Ceph clusters with the solution of your choice at any time, completely independent of OSISM. You don't have to use the path we currently support.

**Comment by Nils98Ar** [comment]
Thank you for the quick answer!
