### ISSUE TITLE
Task "restart ceph osds daemon(s) takes" 1 hour +

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#707]
Seems too long. E.g. when applying `ceph-rgws` or `ceph-mdss`.

![image](https://github.com/osism/issues/assets/48221746/bc523ff3-59fd-4741-a6ef-881ceea336e9)

**Comment by berendt** [comment]
Unfortunately, this is the expected behaviour. The OSD restart handler starts all OSDs one after the other and then waits before each restart until the Ceph cluster is OK again. The more OSDs, the longer it takes. As the OSD restarts are often not necessary, you can deactivate the behaviour from now (OSISM 7.0.3) on by setting `-e ceph_handler_osds_restart=False`.
