### ISSUE TITLE
Use correct versions in osism update manager & environments/manager/run.sh

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#759]
Hi,

I would like to propose to also include all other osism collections and roles into versioning and make them match to the current OSISM release.
In my opinion it is necessary to reliably deploy an release at a later point in time. Currently, the collections and versions use lastest version

Kind regards,
Andre.

**Comment by berendt** [comment]
The versions are configurable with the following environments parameters of the osism update manager command or the run.sh script of the manager environment.

``` 

ANSIBLE_COLLECTION_COMMONS_VERSION (run.sh only)
ANSIBLE_COLLECTION_SERVICES_VERSION
ANSIBLE_PLAYBOOKS_MANAGER_VERSION
``` 

By default main is used. The run.sh script is included in osism/cfg-generics and is synchronized with the help of gilt. It’s possible to add a script that updates the collection versions in the run.sh script in osism/cfg-generics. This way we have the correction version in the configuration repository.

For the osism update manager command the only way to get the versions of the Ansible collections of the next release (without contacting the internet) is to have a look in the run.sh script that’s part of the configuration repository because the configuration repository has to be synced before the manager update.

1. add the sync script to osism/cfg-generics repository and use release tags instead of main by default in the future
2. use the ANSIBLE_COLLECTION_SERVICES_VERSION & ANSIBLE_PLAYBOOKS_MANAGER_VERSION parameters of the run.sh script in the osism update manager command (use main if the script is not available)
