### ISSUE TITLE
radowsgw_interface or radosgw_address required by the RGW service

### ISSUE THREAD

**Issue by berendt** [osism/issues#916]
Add here: https://osism.tech/docs/guides/configuration-guide/ceph#rgw-service

**Comment by mweisbach** [comment]
Christian, as discussed yesterday, both variants needs documentation.

**Option 1**
```
monitor_address: <IP address to be used on this node for mon>
radosgw_address: <IP address to be used on this node for rgw>
```
and to stick it to specific IP addresses, which needs to be present in node's netplan too.

**Option 2**
Use
```
monitor_interface: <mon-interface-name>
radosgw_interface: <rgw-interface-name>
```
to allow 'auto discovery' of the IP address to be used via interface name. But clearly there is a drawback, because this option does not support interfaces with multiple IP addresses (or IP aliases) on.

in the `inventory/host_vars/<nodename>.yml`.

Can you add "ceph" label too?
